Models/PerfilUsuarioViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace GerenciadorDeEmpresaWEB.Models;
public class PerfilUsuarioViewModel
{
    public int Id { get; set; }

    [Required(ErrorMessage = "O nome é obrigatório.")]
    [StringLength(100, MinimumLength = 3, ErrorMessage = "O nome deve ter entre 3 e 100 caracteres.")]
    public string Nome { get; set; }
}

Controllers/PerfilUsuariosController.cs
using GerenciadorDeEmpresaWEB.Models;
using GerenciadorDeEmpresaWEB.Services;
using GerenciadorDeEmpresaWEB.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace GerenciadorDeEmpresaWEB.Controllers
{
    public class PerfilUsuariosController : Controller
    {
        private readonly IPerfilUsuarioServices _perfilUsuarioService;

        public PerfilUsuariosController(IPerfilUsuarioServices perfilUsuarioService)
        {
            _perfilUsuarioService = perfilUsuarioService;
        }

        [HttpGet]
        public async Task<ActionResult<IEnumerable<PerfilUsuarioViewModel>>> Index()
        {
            var result = await _perfilUsuarioService.GetPerfilUsuario();

            if(result is null)
            {
                return View();
            }

            return View(result);
        }

        [HttpGet]
        public async Task<IActionResult> Create() 
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult<PerfilUsuarioViewModel>> Create(PerfilUsuarioViewModel perfilUsuario) 
        {

            if (ModelState.IsValid)
            { 
                var result = await _perfilUsuarioService.CriarPerfilUsuario(perfilUsuario);

                if(result != null)
                    return RedirectToAction(nameof(Index));
            }          

            ViewBag.Erro = "Erro ao criar Empresa";
            return View(perfilUsuario);
        }

        [HttpGet]
        public async Task<IActionResult> Details(int id)
        {
            var perfil = await _perfilUsuarioService.GetPerfilUsuarioPorId(id);

            if (perfil is null)
                return View();

            return View(perfil);
        }


        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var perfil = await _perfilUsuarioService.GetPerfilUsuarioPorId(id);

            if (perfil is null)
                return View();

            return View(perfil);
        }
        [HttpPost]
        public async Task<ActionResult<PerfilUsuarioViewModel>> Edit(int id, PerfilUsuarioViewModel perfil)
        {
            if (ModelState.IsValid)
            {
                var result = await _perfilUsuarioService.AtualizarPerfilUsuario(id, perfil);

                if (result)
                    return RedirectToAction(nameof(Index));
            }
          
            return View(perfil);
        }
        [HttpGet]
        public async Task<ActionResult> Delete(int id)
        {
            var perfil = await _perfilUsuarioService.GetPerfilUsuarioPorId(id);

            if (perfil is null)
                return View();

            return View(perfil);
        }


        [HttpPost, ActionName("DeleteConfirmado")]
        public async Task<IActionResult> DeleteConfirm(int id)
        {
            var result = await _perfilUsuarioService.DeletarPerfilUsuario(id);

            if (result)
                return RedirectToAction("Index");

            return View();
        }
    }
}

Views/PerfilUsuarios/Create.cshtml
@model GerenciadorDeEmpresaWEB.Models.PerfilUsuarioViewModel

@{
    ViewData["Title"] = "Criar Novo Perfil Usuario";
}

<h2>@ViewData["Title"]</h2>

<form asp-action="Create" method="post">
    <div class="form-group">
         <label for="Nome">Nome </label>
        <input asp-for="Nome" class="form-control" />
        <span asp-validation-for="Nome" class="text-danger"></span>
    </div>
    <input type="submit" value="Criar" class="btn btn-success" />
    <a asp-action="Index" class="btn btn-secondary">Retornar</a>

</form>

Views/PerfilUsuarios/Delete.cshtml
@model GerenciadorDeEmpresaWEB.Models.PerfilUsuarioViewModel

@{
    ViewData["Title"] = "Excluir Perfil de Usuario";
}

<h2>@ViewData["Title"]  @Model.Id</h2>

<div>
    <h3>Tem certeza que deseja excluir esse perfil de usuario: <strong>@Model.Nome</strong>?</h3>

    <form asp-action="DeleteConfirmado" method="post">
        <input type="hidden" asp-for="Id" />
        <div class="d-flex justify-content-between mt-4">
                <button type="submit" class="btn btn-danger">Excluir</button>
                <a href="@Url.Action("Index")" class="btn btn-secondary">Cancelar</a>
            </div>
    </form>
</div>

Views/PerfilUsuarios/Details.cshtml
@model GerenciadorDeEmpresaWEB.Models.PerfilUsuarioViewModel

@{
    ViewData["Title"] = "Detalhes do Perfil de Usuario";
}

<h2>@ViewData["Title"]</h2>

<div class="card mt-4">
    <div class="card-header">
        <h4>Informações do Perfil Usuario</h4>
    </div>
    <div class="card-body">
        <div class="row">
            <div class="col-md-6">
                <p><strong>Nome Fantasia:</strong> @Model.Nome</p>
            </div>
        </div>

        <div class="d-flex justify-content-between mt-4">
            <a href="@Url.Action("Edit", new { id = Model.Id })" class="btn btn-primary">Editar</a>
            <a href="@Url.Action("Index")" class="btn btn-secondary">Voltar</a>
        </div>
    </div>
</div>

Views/PerfilUsuarios/Edit.cshtml
@model GerenciadorDeEmpresaWEB.Models.PerfilUsuarioViewModel

@{
    ViewData["Title"] = "Editar Perfil de Usuario";
}

<h2>@ViewData["Title"]</h2>
<div class="card mt-4">
    <div class="card-header">
        <h4>Alterar Dados do Perfil de Usuario</h4>
    </div>
    <div class="card-body">
        <form asp-action="Edit" method="post">
            <div asp-validation-summary="All" class="text-danger mb-3"></div>

            <div class="form-group">
                <label for="Nome">Nome </label>
                <input asp-for="Nome" class="form-control" id="Nome" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
         
            <div class="d-flex justify-content-between mt-4">
                <button type="submit" class="btn btn-success">Salvar</button>
                <a asp-action="Index" class="btn btn-secondary">Voltar</a>
            </div>
        </form>
    </div>
</div>

Views/PerfilUsuarios/Index.cshtml
@model IEnumerable<GerenciadorDeEmpresaWEB.Models.PerfilUsuarioViewModel>

@{
    ViewData["Title"] = "Perfil de Usuarios";
}

<h2>@ViewData["Title"]</h2>

<hr />

<div class="row">
    <div class="col-md-12">
        <div class="pull-left">
            <a asp-action="Create" class="btn btn-primary">
                <span title="Criar Perfil de Usuario" class="fas fa-plus"></span> Adicionar Perfil de Usuario
            </a>

        </div>
    </div>
</div>

<br />

<div class="panel panel-default">
    <table class="table table-striped table-bordered">
        <thead>
            <tr>
                <th>ID</th>
                <th>Nome </th>
                <th>Ações</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var perfilUsuario in Model)
            {
                <tr>
                    <td>@perfilUsuario.Id</td>
                    <td>@perfilUsuario.Nome</td>
                    <td>
                        <a href="@Url.Action("Edit", "PerfilUsuarios", new { id = perfilUsuario.Id })" class="btn btn-warning btn-sm">Editar</a>
                        <a href="@Url.Action("Details", "PerfilUsuarios", new { id = perfilUsuario.Id })" class="btn btn-info btn-sm">Detalhes</a>
                            <a href="@Url.Action("Delete", "PerfilUsuarios", new { id = perfilUsuario.Id })" class="btn btn-danger btn-sm">Excluir</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>